before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
dockers:
  - image_templates:
      - itzg/kube-metrics-reporter:latest
      - itzg/kube-metrics-reporter:{{ .Tag }}
    dockerfile: Dockerfile.release
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - '^misc:'
